version: '2'

services:
  app:
    image: '${service_name}:latest'
    build:
      context: .
    container_name: ${service_name}
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:h2:mem:matches
      - DB_USER=sa
      - DB_PASS=